# Utiliser une image Node.js officielle
FROM node:18-alpine

# Installer Git avec apk (gestionnaire de paquets pour Alpine)
RUN apk add --no-cache git

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json, installer les dépendances en tant que root
COPY package*.json ./

#Installer les dépendances
RUN npm install


# Exposer le port
EXPOSE 3000

# Lancer l'application
CMD ["npm", "run", "dev"]